# Generated by Django 5.0.6 on 2024-09-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16, unique=True)),
                ("mask", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabelId",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZplField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16)),
                ("placeholder", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("zpl", models.TextField()),
                ("labelApp", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="print.labelapp")),
                ("labelId", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="print.labelid")),
            ],
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
                ("ip", models.CharField(max_length=15)),
                ("labelApp", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="print.labelapp")),
                ("labelId", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="print.labelid")),
            ],
            options={
                "verbose_name": "Printer",
                "verbose_name_plural": "Printers",
                "ordering": ("name",),
            },
        ),
    ]
