# Generated by Django 5.0.6 on 2024-09-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="labelApp",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="print.labelapp"),
        ),
        migrations.AlterField(
            model_name="printer",
            name="labelId",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="print.labelid"),
        ),
    ]
