# Generated by Django 5.0.6 on 2024-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0002_alter_printer_labelapp_alter_printer_labelid"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="labelType",
            field=models.CharField(default="IT", max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
