# Generated by Django 5.0.6 on 2024-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0003_label_labeltype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="labelId",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="labelId",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name="LabelId",
        ),
    ]
