# Generated by Django 5.0.6 on 2024-09-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0004_alter_printer_labelid_alter_label_labelid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label_App",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Name", models.CharField(max_length=16, unique=True)),
                ("Mask_App", models.CharField(max_length=16)),
                ("Mask_PRS", models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name="printer",
            name="labelApp",
        ),
        migrations.RemoveField(
            model_name="label",
            name="labelApp",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="labelId",
            new_name="Label_ID",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="labelType",
            new_name="Label_Type",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="labelId",
            new_name="Label_ID",
        ),
        migrations.AddField(
            model_name="label",
            name="Label_App",
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to="print.label_app"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printer",
            name="Label_App",
            field=models.ForeignKey(
                blank=True, default="1", on_delete=django.db.models.deletion.CASCADE, to="print.label_app"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="LabelApp",
        ),
    ]
