# Generated by Django 5.0.6 on 2024-09-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0005_label_app_remove_printer_labelapp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="label",
            old_name="zpl",
            new_name="ZPL_Text",
        ),
    ]
