# Generated by Django 5.0.6 on 2024-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0007_alter_printer_label_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
