# Generated by Django 5.0.6 on 2024-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0008_alter_printer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="Label_ID",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="label",
            name="Label_Type",
            field=models.CharField(max_length=16),
        ),
    ]
