# Generated by Django 5.0.6 on 2024-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0009_alter_label_label_id_alter_label_label_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="Label_Type",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="label_app",
            name="Mask_App",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="label_app",
            name="Name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
